version: '3'

services:
  auth-service:
    build:
      context: ./../auth-service
      dockerfile: ./../auth-service/auth-service.dockerfile
    restart: always
    ports:
      - "50051:50051"
    deploy:
      mode: replicated
      replicas: 1

  logger-service:
    build:
      context: ./../logger-service
      dockerfile: ./../logger-service/logger-service.dockerfile
    restart: always
    ports:
      - "50052:50051"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./logs/:/app/logs

  uts-broker:
    build:
      context: ./../uts-broker
      dockerfile: ./../uts-broker/broker-service.dockerfile
    restart: always
    ports:
      - "3001:3000"
    deploy:
      mode: replicated
      replicas: 1
    expose:
      - "3000"
  
  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fibonachi
      POSTGRES_DB: apps
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/