version: '3'

services:
  uts-broker:
    image: ait0ne666/uts-broker:1.0.0
    ports:
      - '3001:3000'
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    image: ait0ne666/auth-service:1.0.0
    ports:
      - '50051:50051'
    deploy:
      mode: replicated
      replicas: 1

  logger-service:
    image: ait0ne666/logger-service:1.0.0
    ports:
      - '50052:50051'
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./logs/:/app/logs

  postgres:
    image: 'postgres:14.2'
    ports:
      - '5432:5432'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fibonachi
      POSTGRES_DB: apps
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/